### PR TITLE
Fix non-vertically centered Engagements Total in Project summary card

### LINKED ISSUE #426: Project engagement total should be centered
Screen Shot 2020-09-04 at 4 36 26 PM
"1 Language Engagements" was previously in the center of the card vertically, but regressed due to some change.

### PR DESCRIPTION
**Pull request by glassblowerscat**
Closes #426 

Add `alignItems: 'center'` to `cardContent` class and `marginBottom: spacing(2)` to `rightContent` class in `ProjectListItemCard` to fix display issue where UI showing total engagements was not vertically centered

### CODE REVIEW

File: src/components/ProjectListItemCard/ProjectListItemCard.tsx [hunk 1]
```diff
@@ -49,6 +50,7 @@ const useStyles = makeStyles(({ breakpoints, spacing }) => {
     rightContent: {
       flex: 1,
       textAlign: 'right',
+      marginBottom: spacing(2),
```
Comment (CarsonF) [inline src/components/ProjectListItemCard/ProjectListItemCard.tsx:53]: What's this for?

**Review by CarsonF — APPROVED** [review]
Thanks @glassblowerscat!
