### PR TITLE
Fix delete project member when removing all user roles from the form

### LINKED ISSUE #1030: Project > Team Members > Getting "Variable "$input" got invalid value { projectMember: { id: "qlbnnbh4KRK", roles: [Array] }, submitAction: "delete" }; Field "submitAction" is not defined by type "UpdateProjectMemberInput"." error when the user deletes the team member after removing the role
**Roles:** All

**Describe the bug**
Project > Team Members > Getting `Variable "$input" got invalid value { projectMember: { id: "qlbnnbh4KRK", roles: [Array] }, submitAction: "delete" }; Field "submitAction" is not defined by type "UpdateProjectMemberInput".` error when the user deletes the team member after removing the role

**Steps to Reproduce**
1. Login as a root user
2. Create a project and open a project detail page
3. Add `Team Member`.
4. Click on the 'Submit' button.
5. Click on the edit icon and remove the added 'Roles'.
6. Click on the delete button.

**Expected Result**
Better Validation Message should be displayed.

**Actual Result**
Getting `Variable "$input" got invalid value { projectMember: { id: "qlbnnbh4KRK", roles: [Array] }, submitAction: "delete" }; Field "submitAction" is not defined by type "UpdateProjectMemberInput".` error when the user deletes the team member after removing the role

See video - 

https://user-images.githubusercontent.com/5212585/143002546-44b8976d-db6d-4971-860e-ea9df0834915.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 694a111
CordAPIV3# cfbf82c

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #1030

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
Thanks @daniel-leod!

Can you move the `deleteProjectMember` call from the `onClick` to the `onSubmit` handler as well? The way it currently works the dialog does not wait for the mutation to call to finish.

File: src/scenes/Projects/Members/Update/UpdateProjectMember.tsx [hunk 1]
```diff
@@ -66,10 +72,11 @@ export const UpdateProjectMember = ({
 
   const availableRoles = data?.user.roles.value ?? [];
   return (
-    <DialogForm<UpdateProjectMemberInput>
+    <DialogForm<FormShape>
       title="Update Team Member Role"
       closeLabel="Close"
       submitLabel="Save"
+      sendIfClean
```
Comment (CarsonF) [inline src/scenes/Projects/Members/Update/UpdateProjectMember.tsx:79]:
```suggestion
      sendIfClean="delete"
```
If there aren't role changes we should make an update call.

**Review by CarsonF — APPROVED** [review]
Thanks @daniel-leod!
