### PR TITLE
Invalidate entire project object if removing self from project team

### LINKED ISSUE #823: Project > Team member > "Add Partnership" button is displayed even team member is removed from "Financial Analyst" user
**Roles:** Financial Analyst

**Describe the bug**
Project > Team member > `Add Partnership` button is displayed even team member is removed from `Financial Analyst` user 

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Login as a `Financial Analyst` user and click on the `Partnership` button
4. Logout the `Financial Analyst`  user and log in as an `Admin` user
5. Click on the `Team Members` button
6. Add  `Financial Analyst` as a team member
7. Login as a `Financial Analyst` user
8. Click on the `Partnership` button
9. Back to the project detail page and removed `Financial Analyst` user from team member
10. Again click on the `Partnership` button

**Expected Result**
 `Add Partnership` button should not be displayed after removing the `Financial Analyst` team member

**Actual Result**
 `Add Partnership` button is displayed even team member is removed from the `Financial Analyst` user 

See video - 

https://user-images.githubusercontent.com/5212585/115718533-0c985680-a330-11eb-8bcc-005083d00a2e.mp4

image

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 71c8ecb5

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #823

### CODE REVIEW

File: src/scenes/Projects/Members/Update/UpdateProjectMember.tsx [hunk 1]
```diff
@@ -55,16 +55,29 @@ export const UpdateProjectMember = ({
...
+        invalidateProps(cache, project, [
+          'partnerships',
+          'team',
+          'rootDirectory',
+          'narrativeReports',
+          'financialReports',
+          'budget',
+        ]);
+      }
+    },
```
Comment (CarsonF) [inline src/scenes/Projects/Members/Update/UpdateProjectMember.tsx:80]: `removeItemFromList` is expecting to be given directly to the `update` option (or merged via `callAll`). Right now this function isn't even being called.
You need to do
```ts
removeItemFromList({...})(cache, ...);
```

Also I think the second removeItemFromList isn't needed if we are removing the whole object.

**Comment by CarsonF** [comment]
Since we didn't have a helper function I went ahead and added. I also rebased and used it. Can you take a look and confirm it still solves the original issue?

**Comment by daniel-leod** [comment]
@CarsonF Yes, just tested it out and it works fine.

**Review by CarsonF — APPROVED** [review]
