### PR TITLE
Fix "undefined" search input value

### LINKED ISSUE #504: Search > "undefined" keyword is displayed when clearing the search box
**Describe the bug**
Search > `undefined` keyword is displayed when clearing the search box

**Steps to Reproduce**
1. Login
2. Click on the `search box` and search project i.e. `filter`
3. Clear `search box` and hit the enter

**Expected Result**
The search box should be cleared

**Actual Result**
`undefined` keyword is displayed when clearing the search box
See video-  https://drive.google.com/file/d/16p9bdM4qzrujbGpwJiDygi539U4aUR_J/view?usp=sharing

cord-field# b1ebad03

### PR DESCRIPTION
**Pull request by glassblowerscat**
Closes #504 

- Update `HeaderSearch` form `onSubmit` function to only update URL search query if input value is defined

### CODE REVIEW

File: src/scenes/Root/Header/HeaderSearch/HeaderSearch.tsx [hunk 1]
```diff
@@ -26,11 +26,16 @@ export const HeaderSearch: FC = () => {
   const classes = useStyles();
   const [{ q: search = '' }] = useSearch();
   const navigate = useNavigate();
+  console.log('search', search);
```
Comment (CarsonF) [inline src/scenes/Root/Header/HeaderSearch/HeaderSearch.tsx:29]:
```suggestion
```

File: src/scenes/Root/Header/HeaderSearch/HeaderSearch.tsx [hunk 2]
```diff
@@ -26,11 +26,16 @@ export const HeaderSearch: FC = () => {
...
 
   return (
     <Form
       initialValues={{ search }}
-      onSubmit={({ search }) => navigate(`/search?q=${search}`)}
+      onSubmit={({ search }) => {
+        if (search !== undefined) {
```
Comment (CarsonF) [inline src/scenes/Root/Header/HeaderSearch/HeaderSearch.tsx:35]: I would be cool with a null or even falsely check here FWIW

**Comment by glassblowerscat** [comment]
@CarsonF Okay, I made that just a simple "truthy" check; it's ready to review again

**Review by CarsonF — APPROVED** [review]
Sweet!
