### PR TITLE
Tweak Completion Description

### LINKED ISSUE #928: Project > Create product > "Completion Description" field data is not displayed in proper alignment
Roles All

**Describe the bug**
Project > Create product > `Completion Description` field data is not displayed in proper alignment

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and Open created project
3. Add `Start-End` date and Create `LanguageEngagment`
4. Click on the `View` button
5. Click on the `Add product` button  and Add product details
6. Enter Unlimited data in the `Completion Description` field
7. Click on the `Submit` button and click on the `Edit` product button

**Expected Result**
`Completion Description` field data should be displayed in Proper alignment
 
**Actual Result**
`Completion Description` field data is not displayed in proper alignment

See video -

https://user-images.githubusercontent.com/5212585/129570143-722fd91e-3f7b-42bc-9ba0-19e9a6eab066.mp4

processed

**FYI**@ParkeBrown @michaelmarshall

cord-field# 1fc2795
CordAPIV3# 9190940

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #928

### CODE REVIEW

**Review by CarsonF — COMMENTED** [review]
Isn't this already how it works?

**Comment by daniel-leod** [comment]
@CarsonF Just tested on https://dev.cordfield.com/ and latest version of `develop`. This is how it looks:
image

File: src/scenes/Products/Detail/ProductInfo.tsx [hunk 1]
```diff
@@ -25,6 +25,9 @@ const useStyles = makeStyles(() => ({
   listItem: {
     margin: 0,
   },
+  completionDescription: {
+    wordWrap: 'break-word',
```
Comment (CarsonF) [inline src/scenes/Products/Detail/ProductInfo.tsx:29]: It looks like this is deprecated.
It suggests to use this instead:
```css
overflow-wrap: break-word;
```

**Review by CarsonF — CHANGES_REQUESTED** [review]

**Review by CarsonF — APPROVED** [review]
